### PR TITLE
Visual feedback on mobile&desktop

### PR DESCRIPTION
**Pull request by Entkenntnis**
## Description

First of all: Thank you for this great library. It's really useful und customizable.

There is only one thing missing: proper visual feedback. Hassling around with `:active` was not satisfying for mobile, so my suggestion would be to handle the active state of a button with javascript.

This PR toggles a `hg-activeButton` class on the currently pressed button. You can now style the button with css. The styling is consistent between desktop and Chrome / FF. I wasn't able to test it on iOS yet. Add `autoUseTouchEvents` to the BasicDemo to test it on mobile.

I would be glad if you could review this PR.

Tests are running fine, the documentation script was not found?

## Checks

- [x] Tests ( `npm run test -- --coverage` ) Coverage at `./coverage/lcov-report/index.html` should be 100%

### CODE REVIEW

**Comment by hodgef** [comment]
Thanks for this addition @Entkenntnis, it's a clear improvement over the `:active` approach.
I'll be merging this shortly!

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Now released as of simple-keyboard `2.26.19`. Thanks again 🎉

**Comment by Entkenntnis** [comment]
Cool! Could you also update react-simple-keyboard?

**Comment by hodgef** [comment]
Hello @Entkenntnis,
react-simple-keyboard 2.0.26 should have the latest changes :)
https://github.com/hodgef/react-simple-keyboard/pull/259

Regards,
Francisco Hodge

**Pull request merged**
