### PR TITLE
refactor: some classes and tests

### PR DESCRIPTION
**Pull request by MadDeveloper**
I did some refactors, but not as much as I wanted. Maybe I'll do more later. I hadn't break tests, let me know if something is broken 👍

### CODE REVIEW

**Comment by hodgef** [comment]
Hey @MadDeveloper it seems the tests have not passed. Could you check it out? I'll review the commits shortly. Thanks!

**Comment by MadDeveloper** [comment]
It's not the tests, it's codecov.

**Comment by hodgef** [comment]
Haha, yes I meant the checks. The PR is nice! Only thing so far that I can see causing a problem are the arrow functions, I had them in initially but had to remove them since they basically attach to the instance (they're not proper methods). So it broke the modules implementation. Other than that I think we're good, I'll pull down the PR to check further. Thanks

**Comment by MadDeveloper** [comment]
Sorry I've never used Codecov, and I don't see an explicit error on the report, so what's wrong with arrow functions? 😅

**Comment by MadDeveloper** [comment]
Ok, so if I remove arrow functions, this PR won't be useful anymore. Furthermore, I didn't applied all the changes I would have wanted, so I'll just close this PR and maybe do a better one someday.

**Comment by hodgef** [comment]
I understand - Thanks for bringing forward these quality PRs, your contributions are always welcome.

Regards,
Francisco Hodge

**Pull request closed without merging**
