### PR TITLE
Upgrade to support ESModules and Angular 13

### PR DESCRIPTION
**Pull request by coldkick2**
Add support for ECMAScript Modules
 * package.json
   * Upgrade webpack (5.40.0 > 5.65.0)
   * Set module location (build/index.modern.js)
 * package-lock.json
   * Update package resolutions
 * .npmignore
   * Add webpack.config.modern.js to the exclusion list
 * TSConfig
   * Target ES2020 to improve minification
   * Enable ESModule Interoperability for compatibility in Node
 * Webpack Config
   * Explicitly used the array-push chunkFormat for compatibility
 * Webpack Modern Config
   * Target the last two major browser versions
   * Update the libraryTarget to 'module'
   * Update the chunkFormat to 'module'
   * Remove the library configuration as it unsupported with
     libraryTarget 'module'
   * Enable experimental module output
 * build/index.modern.js
   * Update to the built ESModule output

## Description

Add support for ECMAScript Modules.
Angular 13+ no longer supports UMD modules (https://github.com/angular/angular/issues/38366)

## Checks

- [x] Tests ( `npm run test -- --coverage` ) Coverage at `./coverage/lcov-report/index.html` should be 100%

### CODE REVIEW

**Comment by hodgef** [comment]
Hey @coldkick2, thank you for these improvements! They're great additions, although I do have one concern:

Perhaps changing `index.modern.js` is not the right approach, as it appears to be a breaking change: `index.js` and `index.modern.js` are no longer interchangeable in [CDN implementations](https://hodgef.com/simple-keyboard/getting-started/) due to the missing `libraryTarget`.

In my opinion, it would be nice to keep allowing users to opt-out of the polyfills by swapping `index.js` with `index.modern.js` without any extra requirements.

**Before:**
image

**After:**
image

One way to do this is to create a separate `index.esm.js` or `index.module.js` (or something like that), instead of editing `index.modern.js`. To accomplish this, this new file would need its own typings setup, Webpack config, etc.

Once again thank you for putting forward these improvements.

Regards,
Francisco Hodge

**Comment by coldkick2** [comment]
> Hey @coldkick2, thank you for these improvements! They're great additions, although I do have one concern:
> 
> Perhaps changing `index.modern.js` is not the right approach, as it appears to be a breaking change: `index.js` and `index.modern.js` are no longer interchangeable in [CDN implementations](https://hodgef.com/simple-keyboard/getting-started/) due to the missing `library` name.
> 
> In my opinion, it would be nice to keep allowing users to opt-out of the polyfills by swapping `index.js` with `index.modern.js` without any extra requirements.
> 
> **Before:** image
> 
> **After:** image
> 
> One way to do this is to create a separate `index.esm.js` or `index.module.js` (or something like that), instead of editing `index.modern.js`. This new file would need its own typings setup / Webpack config however.
> 
> Once again thank you for putting forward these improvements.
> 
> Regards, Francisco Hodge

Very good points! I had actually attempted to create it as a .esm.js file but it threw some strange webpack-cli errors about needing an esm module. I will look into this shortly and add a new commit to the pull taking in your suggestions.

**Comment by coldkick2** [comment]
I have pushed down some pretty big changes to the distribution model. Let me know if this seems like too much. The need for scoped package.json (monorepo style) necessitated separate folders.

**Comment by hodgef** [comment]
Thanks for the update @coldkick2! Unfortunately, it seems that this does change things a bit more than I'd like. Let me explain my reasoning:

In my view, simple-keyboard (and [related repos sharing the same Webpack boilerplate](https://gitlab.com/users/hodgef/projects)) is a "stable" project as of now, meaning that the setup works and file sizes are satisfactory. Unless changing setup would yield insanely smaller files there's frankly no real incentive to change. I am not as concerned about build times since I only commit every now and then when someone raises an issue. Most of the times it's Dependabot triggering builds and I don't mind about that case as I'm not waiting around for CI builds to complete.

Now what interested me the most in the initial proposal is the improved support for Angular 13 (hope I got that right). That being said, I don't think this is worth refactoring the build process or bringing along breaking changes.

**So to sum it up**: The project is stable now with rather minimal maintenance, and I would like to keep it that way as much as possible. If Angular users would benefit from a separate index.esm.js build, I would be all for it on condition that it doesn't increase maintenance, require considerable docs updates or bring along breaking changes for those that do not need the esm version.

Out of curiosity though, is ESM needed for Angular 13 because of tree shaking? Or are there other improvements that an Angular 13 user would benefit from vs [when using the current UMD builds](https://stackblitz.com/edit/angular-u4f4io?file=src%2Fapp%2Fapp.component.ts)?

I think that if there's a strong reason to make a change I would be eager to move forward now, but if not it's probably best to keep this as a Proposal until there's a strong benefit/incentive.

Thanks again for the contributions and sorry for the long-winded post!

Regards,
Francisco Hodge

**Comment by coldkick2** [comment]
No problem @hodgef . It’s a required change. Without switching from umd, webpack bundles simply do not work with angular anymore and the keyboard will fail to load. We ran local tests on our application which we upgraded from 11 and the keyboard would no longer render. I made the ESM patch and tested it locally in our project and it resolved the issue.

**Comment by hodgef** [comment]
> No problem @hodgef . It’s a required change. Without switching from umd, webpack bundles simply do not work with angular anymore and the keyboard will fail to load. We ran local tests on our application which we upgraded from 11 and the keyboard would no longer render. I made the ESM patch and tested it locally in our project and it resolved the issue.

Hey @coldkick2, it appears to work in this sandbox [forked from the docs example](https://angular.io/start#create-the-sample-project):
https://stackblitz.com/edit/angular-u4f4io?file=src%2Fapp%2Fapp.component.ts
I will try to install it locally to confirm and share a test repo if I can.

**Comment by coldkick2** [comment]
Here is the issue we are seeing:
import-error

It is caused when our base application is extended upon by another project.

It appears that webpack loses the esInterop flags or tree shakes out some necessary handlers to import the project when on angular 13, so it fails to load.

**Comment by hodgef** [comment]
Do you mind sharing a repro (e.g: test git repo) for this issue? It's quite weird as I'm able to load simple-keyboard without issues in Angular 13, so I would like to debug the issue you're seeing. Thanks!

**Comment by coldkick2** [comment]
Hey, to repro will take a lot of time (that I do not have at the moment)
What I can tell you about the situation is this:

We are using NX 13 to create an Angular monorepo.
The angular monorepo has a library that incudes simple-keyboard and exports a keyboard component.

We have a customer that is implementing our library and overrides the keyboard with their own customized layout.

When they build their custom app using Nx's build tools, webpack fails to load the imported module.

By making simple-keyboard ESM compatible it fixes the resolution issue.

**Pull request closed without merging**
